"""
配置模块
包含模型配置和系统提示词
"""

from .models import (
    AVAILABLE_MODELS,
    FILE_UPLOAD_SUPPORTED_MODELS,
    SUPPORTED_FILE_TYPES
)

from .prompts import (
    GENERATE_PRD_SYSTEM_PROMPT,
    INITIAL_FIX_SYSTEM_PROMPT,
    DEVELOPER_REVIEW_PROMPT,
    PLANNER_FIX_PROMPT,
    CHECKLIST,
    REPORT_ASSISTANT_SYSTEM_PROMPT,
    WEEKLY_REPORT_SYSTEM_PROMPT,
    WHITEPAPER_ASSISTANT_SYSTEM_PROMPT,
    SELF_CHECK_SYSTEM_PROMPT
)

__all__ = [
    "AVAILABLE_MODELS",
    "FILE_UPLOAD_SUPPORTED_MODELS",
    "SUPPORTED_FILE_TYPES",
    "GENERATE_PRD_SYSTEM_PROMPT",
    "INITIAL_FIX_SYSTEM_PROMPT",
    "DEVELOPER_REVIEW_PROMPT",
    "PLANNER_FIX_PROMPT",
    "CHECKLIST",
    "REPORT_ASSISTANT_SYSTEM_PROMPT",
    "WEEKLY_REPORT_SYSTEM_PROMPT",
    "WHITEPAPER_ASSISTANT_SYSTEM_PROMPT",
    "SELF_CHECK_SYSTEM_PROMPT"
]
